# Generated by Django 4.0.1 on 2022-02-14 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dishes', '0006_remove_comment_like_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeCommentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.AddField(
            model_name='comment',
            name='like1',
            field=models.ManyToManyField(related_name='liked_comment', through='dishes.LikeCommentUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likecommentuser',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user_table', to='dishes.comment'),
        ),
        migrations.AddField(
            model_name='likecommentuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_comment_table', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likecommentuser',
            unique_together={('user', 'comment')},
        ),
    ]
