# Generated by Django 4.0.1 on 2022-02-21 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planes', '0007_likecommentuser_remove_comment_like_comment_like1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like1',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='users_likes',
            field=models.ManyToManyField(related_name='liked_comment', through='planes.LikeCommentUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
