# Generated by Django 4.0.1 on 2022-02-21 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0008_remove_comment_like1_comment_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='Model', max_length=100, verbose_name='Модель')),
                ('specifications', models.CharField(max_length=200, verbose_name='Характеристики')),
                ('reference', models.TextField(verbose_name='Справка')),
                ('image', models.ImageField(upload_to='planes/', verbose_name='Изображение')),
                ('nation', models.CharField(max_length=50, verbose_name='Нация')),
                ('url', models.SlugField(max_length=150, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planes.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Самолёт',
                'verbose_name_plural': 'Самолёты',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dish',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.AddField(
            model_name='comment',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='planes.airplane'),
        ),
    ]
