# Generated by Django 4.0.1 on 2022-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0009_airplane_remove_comment_dish_delete_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
    ]
