# Generated by Django 4.0.1 on 2022-02-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0010_alter_airplane_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='specifications',
            field=models.CharField(max_length=300, verbose_name='Характеристики'),
        ),
    ]
