# Generated by Django 4.0.1 on 2022-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0011_alter_airplane_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='specifications',
        ),
        migrations.AddField(
            model_name='airplane',
            name='constructor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Конструктор'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='cruising_speed',
            field=models.CharField(blank=True, max_length=5, verbose_name='Крейсерская скорость'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='engine_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='production_volume',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
