# Generated by Django 4.0.1 on 2022-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0013_alter_airplane_cruising_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='constructor',
            field=models.CharField(max_length=30, null=True, verbose_name='Конструктор'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='engine_type',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип двигателя'),
        ),
    ]
