# Generated by Django 4.0.1 on 2022-02-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0014_alter_airplane_constructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='production_volume',
            field=models.PositiveIntegerField(default=0, verbose_name='Единиц произведено'),
        ),
    ]
