# Generated by Django 4.0.1 on 2022-02-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0016_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.nation', verbose_name='Нация'),
        ),
    ]
