# Generated by Django 4.0.1 on 2022-02-22 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planes', '0017_alter_airplane_nation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAirplaneUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='airplane',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airplane',
            name='users_likes',
            field=models.ManyToManyField(related_name='liked_airplane', through='planes.LikeAirplaneUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likeairplaneuser',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user_table', to='planes.airplane'),
        ),
        migrations.AddField(
            model_name='likeairplaneuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_airplane_table', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likeairplaneuser',
            unique_together={('user', 'model')},
        ),
    ]
