# Generated by Django 4.0.1 on 2022-02-22 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planes', '0018_likeairplaneuser_airplane_likes_airplane_users_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='tag',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TagAirplaneUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taged_user_table', to='planes.airplane')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taged_airplane_table', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'model')},
            },
        ),
    ]
