# Generated by Django 4.0.1 on 2022-02-22 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planes', '0019_airplane_tag_tagairplaneuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='users_tags',
            field=models.ManyToManyField(related_name='taged_plane', through='planes.TagAirplaneUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
