# Generated by Django 4.0.1 on 2022-03-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0030_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsModel',
        ),
    ]
