# Generated by Django 4.0.1 on 2022-03-24 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0031_rename_news_newsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='nation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planes.nation', verbose_name='Нация'),
        ),
    ]
