# Generated by Django 4.0.1 on 2022-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0032_alter_airplane_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='model',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Модель'),
        ),
    ]
